version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./data:/usr/share/nginx/data:ro
      - ./conf:/etc/nginx/conf.d
#    networks:
#      - mynet
    ports:
      - 80:80

#networks:
#  external: true
#  name: mynet
